<a href="https://colab.research.google.com/github/khoihole329-sudo/my-website/blob/main/dulieuxettuyendaihoc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

**Tải dữ liệu xét tuyển đại hoc**

In [ ]:
df = pd.read_csv('dulieuxettuyendaihoc.csv', index_col='STT')
df.head(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,NaN,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,NaN,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,NaN,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,NaN,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,NaN,2NT,4.25,4.50,5.00,A
6,9.3,7.6,7.9,8.6,7.0,7.3,7.7,7.9,9.6,7.8,...,5.7,8.0,7.8,M,NaN,1,1.50,4.00,6.00,D1
7,2.8,3.9,5.5,6.9,5.0,7.3,4.6,5.2,4.4,6.7,...,6.6,6.0,6.0,F,NaN,2,6.50,6.75,5.25,C
8,8.3,6.0,7.6,5.1,7.5,4.7,5.8,7.2,6.7,6.3,...,7.1,6.8,7.0,F,NaN,2,3.75,4.50,4.25,D1
9,6.5,6.3,7.6,6.0,5.5,7.1,6.3,5.0,7.3,6.8,...,9.1,7.9,6.1,F,NaN,1,3.50,3.50,6.75,D1
10,7.3,5.9,4.7,7.1,6.7,7.9,6.7,7.7,8.0,6.8,...,6.4,6.1,7.8,F,NaN,1,4.00,4.75,5.50,D1

In [ ]:
df.tail(10)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
91,8.1,7.7,9.1,8.5,6.1,8.6,8.8,7.3,8.8,8.3,...,8.3,8.7,7.8,M,NaN,2,6.25,4.00,6.50,A
92,7.8,6.5,6.7,5.4,6.2,4.8,5.9,4.4,8.9,6.9,...,7.2,7.4,7.0,M,NaN,2NT,4.75,4.75,4.50,A
93,5.0,6.6,6.5,7.2,5.8,6.7,6.4,6.0,6.8,6.1,...,5.9,6.7,5.8,M,NaN,1,3.25,5.25,4.25,A
94,5.2,5.2,6.8,7.9,6.6,8.9,7.6,5.3,6.8,5.8,...,8.7,7.8,5.0,M,NaN,1,3.50,4.25,5.00,A
95,5.8,5.9,7.6,6.1,5.3,8.1,6.1,5.0,6.4,7.2,...,7.3,6.8,5.3,M,NaN,1,4.25,2.50,4.75,A
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,NaN,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,NaN,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,NaN,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,NaN,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,NaN,2NT,5.25,2.50,4.25,C

In [ ]:
#Thống kê dữ liệu thiếu cho cột dân tộc và hiệu chỉnh dữ liệu thiếu như sau: Mặc định thiếu
# thì điền giá trị 0.

df['DT'].fillna(0, inplace=True)
df

/tmp/ipykernel_7087/1359951400.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['DT'].fillna(0, inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [ ]:
# Thống kê dữ liệu thiếu cho biến T1 và hiệu chỉnh dữ liệu, lưu ý việc thay thế dữ liệu thiếu sử
#dụng phương pháp Mean
df['T1'].fillna(df['T1'].mean(), inplace=True)
df

/tmp/ipykernel_7087/867632662.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['T1'].fillna(df['T1'].mean(), inplace=True)

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,X6,D6,N6,GT,DT,KV,DH1,DH2,DH3,KT
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,6.6,7.6,5.9,F,0.0,2NT,3.25,3.25,4.50,A1
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.6,6.1,4.4,M,0.0,1,6.00,4.00,3.50,C
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,7.9,8.1,4.6,M,0.0,1,5.00,6.75,4.00,C
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,7.1,7.3,7.4,M,0.0,1,4.25,4.25,5.25,D1
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,6.1,7.5,7.2,M,0.0,2NT,4.25,4.50,5.00,A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,6.3,6.1,6.2,F,0.0,1,5.25,1.50,6.25,C
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,7.9,7.5,4.4,F,0.0,1,5.25,3.75,4.75,C
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,9.6,8.4,5.8,M,0.0,2NT,7.00,8.00,4.00,C
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,6.6,5.2,5.9,M,0.0,1,5.00,3.50,5.50,C
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.6,6.6,5.8,M,0.0,2NT,5.25,2.50,4.25,C

In [ ]:
# Hãy thực hiện xử lý lần lượt tất cả dữ liệu thiếu cho các biến về điểm số còn lại.
df[i]=df[i].fillna(df[i].mean())

df

,T1,L1,H1,S1,V1,X1,D1,N1,T2,L2,...,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3,XL1,XL2,XL3
STT,,,,,,,,,,,,,,,,,,,,,
1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,8.9,...,3.25,3.25,4.50,A1,7.00,7.54,7.06,K,K,K
2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,5.4,...,6.00,4.00,3.50,C,4.69,5.47,4.70,Y,TB,Y
3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,4.9,...,5.00,6.75,4.00,C,5.77,5.38,4.33,TB,TB,Y
4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,6.2,...,4.25,4.25,5.25,D1,6.21,5.20,6.03,TB,TB,TB
5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,5.5,...,4.25,4.50,5.00,A,6.50,6.36,7.01,K,TB,K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,6.8,...,5.25,1.50,6.25,C,7.43,7.42,7.04,K,K,K
97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,4.8,...,5.25,3.75,4.75,C,4.93,5.15,4.78,Y,TB,Y
98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,7.3,...,7.00,8.00,4.00,C,7.05,7.84,7.92,K,K,K
99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,5.7,...,5.00,3.50,5.50,C,4.15,4.72,6.16,Y,Y,TB
100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,6.4,...,5.25,2.50,4.25,C,5.26,5.72,5.90,TB,TB,TB

In [ ]:
#  Tạo các biến TBM1, TBM2, TBM3 tương ứng với trung bình môn của các năm lớp 10, 11 và
12.
df['TBM1']=(df['T1']*2+df['L1']+df['H1']+df['S1']+df['V1']*2+df['X1']+df['D1']+df['N1'])/10

df['TBM2']=(df['T2']*2+df['L2']+df['H2']+df['S2']+df['V2']*2+df['X2']+df['D2']+df['N2'])/10

df['TBM3']=(df['T3']*2+df['L3']+df['H3']+df['S3']+df['V3']*2+df['X3']+df['D3']+df['N3'])/10

df

,STT,T1,L1,H1,S1,V1,X1,D1,N1,T2,...,GT,DT,KV,DH1,DH2,DH3,KT,TBM1,TBM2,TBM3
0,1,7.2,7.3,6.3,7.3,7.0,7.9,7.3,5.5,8.4,...,F,NaN,2NT,3.25,3.25,4.50,A1,7.00,7.54,7.06
1,2,5.4,3.9,3.9,4.0,5.4,5.4,5.3,2.8,6.3,...,M,NaN,1,6.00,4.00,3.50,C,4.69,5.47,4.70
2,3,5.6,6.8,7.2,7.5,4.3,7.4,5.8,3.2,5.0,...,M,NaN,1,5.00,6.75,4.00,C,5.77,5.38,4.33
3,4,6.6,6.4,5.3,6.9,5.4,7.3,6.4,5.8,5.1,...,M,NaN,1,4.25,4.25,5.25,D1,6.21,5.20,6.03
4,5,6.0,5.0,6.0,7.3,6.5,7.7,7.9,6.1,5.4,...,M,NaN,2NT,4.25,4.50,5.00,A,6.50,6.36,7.01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,96,8.6,6.9,7.4,8.8,7.6,5.8,7.3,5.7,8.9,...,F,NaN,1,5.25,1.50,6.25,C,7.43,7.42,7.04
96,97,3.7,5.4,6.0,5.1,5.5,3.9,6.1,4.4,4.1,...,F,NaN,1,5.25,3.75,4.75,C,4.93,5.15,4.78
97,98,8.8,5.5,7.4,7.7,6.2,7.3,8.1,4.5,9.5,...,M,NaN,2NT,7.00,8.00,4.00,C,7.05,7.84,7.92
98,99,2.7,1.8,3.4,5.3,4.5,7.9,4.9,3.8,2.8,...,M,NaN,1,5.00,3.50,5.50,C,4.15,4.72,6.16
99,100,4.1,5.2,4.9,5.3,5.5,5.4,7.2,5.4,4.4,...,M,NaN,2NT,5.25,2.50,4.25,C,5.26,5.72,5.90

In [ ]:
##8. Tạo các biến xếp loại XL1, XL2 và XL3 dựa trên TBM1,TBM2 và TBM3 cho từng năm lớp
#10, 11, 12 như sau:
#• Nhỏ hơn 5.0 xếp loại: yếu (kí hiệu là Y)
#• Từ 5.0 đến dưới 6.5: trung bình (kí hiệu là TB)
#• Từ 6.5 đến dưới 8.0: khá (kí hiệu là K)
#• Từ 8.0 đến dưới 9.0: giỏi (kí hiệu là G)
#• Từ 9.0 trở lên: xuất sắc (kí hiệu là XS)
# Hàm xếp loại
def xeploai(diem):
    if diem < 5:
        return 'Y'
    elif diem < 6.5:
        return 'TB'
    elif diem < 8:
        return 'K'
    elif diem < 9:
        return 'G'
    else:
        return 'XS'
df['XL1'] = df['TBM1'].apply(xeploai)
df['XL2'] = df['TBM2'].apply(xeploai)
df['XL3'] = df['TBM3'].apply(xeploai)

df[['TBM1','XL1','TBM2','XL2','TBM3','XL3']].head(10)

   TBM1 XL1  TBM2 XL2  TBM3 XL3
0  7.00   K  7.54   K  7.06   K
1  4.69   Y  5.47  TB  4.70   Y
2  5.77  TB  5.38  TB  4.33   Y
3  6.21  TB  5.20  TB  6.03  TB
4  6.50   K  6.36  TB  7.01   K
5  7.96   K  8.54   G  7.82   K
6  4.90   Y  5.60  TB  5.24  TB
7  6.80   K  6.87   K  6.95   K
8  6.23  TB  6.72   K  6.59   K
9  6.80   K  7.25   K  7.12   K

In [ ]:
## Tạo các biến US_TBM1, US_TBM2 và US_TBM3 để chuyển điểm trung bình các năm lớp
#10, 11 và 12 từ thang điểm 10 của Việt Nam sang thang điểm 4 của Mỹ. Sử dụng phương
#pháp Min-Max Normalization

df['US_TBM1'] = (df['TBM1'] - 0)/(10 - 0) * 4
df['US_TBM2'] = (df['TBM2'] - 0)/(10 - 0) * 4
df['US_TBM3'] = (df['TBM3'] - 0)/(10 - 0) * 4
df[['TBM1','US_TBM1','TBM2','US_TBM2','TBM3','US_TBM3']].head(10)

   TBM1  US_TBM1  TBM2  US_TBM2  TBM3  US_TBM3
0  7.00    2.800  7.54    3.016  7.06    2.824
1  4.69    1.876  5.47    2.188  4.70    1.880
2  5.77    2.308  5.38    2.152  4.33    1.732
3  6.21    2.484  5.20    2.080  6.03    2.412
4  6.50    2.600  6.36    2.544  7.01    2.804
5  7.96    3.184  8.54    3.416  7.82    3.128
6  4.90    1.960  5.60    2.240  5.24    2.096
7  6.80    2.720  6.87    2.748  6.95    2.780
8  6.23    2.492  6.72    2.688  6.59    2.636
9  6.80    2.720  7.25    2.900  7.12    2.848

In [ ]:
## 10. Tạo biến kết quả xét tuyển (kí hiệu là KQXT) nhằm xác định sinh viên đậu (giá trị “1”) và
# rớt ( giá trị “0”) vào các khối dựa trên điểm DH1, DH2 và DH3 như sau
# • Với khối A, A1 nếu [(DH1*2 + DH2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu,
# ngược lại là rớt
# • Với khối B nếu [(DH1 + DH2*2 + DH3)/4] lớn hơn hoặc bằng 5.0 thì đậu, ngược
# lại là rớt
# • Với khối khác nếu [(DH1+ DH2 + DH3)/3] lớn hơn hoặc bằng 5.0 thì đậu, ngược
# lại là rớt
# 1. Định nghĩa hàm xét tuyển dựa trên dữ liệu của từng sinh viên (từng dòng)
def xet_tuyen(row):
    if row['KT'] in ['A','A1']:
        diem = (row['DH1']*2 + row['DH2'] + row['DH3'])/4
    elif row['KT'] == 'B':
        diem = (row['DH1'] + row['DH2']*2 + row['DH3'])/4
    else:
        diem = (row['DH1'] + row['DH2'] + row['DH3'])/3

    return 1 if diem >= 5 else 0

df['KQXT'] = df.apply(xet_tuyen, axis=1)
df[['KT','DH1','DH2','DH3','KQXT']].head()

   KT   DH1   DH2   DH3  KQXT
0  A1  3.25  3.25  4.50     0
1   C  6.00  4.00  3.50     0
2   C  5.00  6.75  4.00     1
3  D1  4.25  4.25  5.25     0
4   A  4.25  4.50  5.00     0

In [ ]:
# Lưu file
df.to_csv('processed_dulieuxettuyendaihoc.csv', index=False)

# Kiểm tra file đã tồn tại chưa
import os
print(os.listdir())

['.config', 'processed_dulieuxettuyendaihoc.csv', 'dulieuxettuyendaihoc.csv', 'sample_data']

In [ ]:
from google.colab import files
files.download('processed_dulieuxettuyendaihoc.csv')